---
<<<<<<< Updated upstream
title: "Takım: R-U-OK ?"
=======
title: "Takım: R U OK"
>>>>>>> Stashed changes
sidebar: false 
---

MUY665-İş Analitiği dersi R U OK takım sayfamıza hoş geldiniz.

Bu sayfada yıl içerisinde gerçekleştireceğimiz analitik çalışmalarımızı paylaşıyoruz.

Lütfen faaliyetlerimizi görmek için için bizi takipte kalın.

## Takım Üyeleri

<<<<<<< Updated upstream
1.  [Eda Balaban](/takim/edabalaban.qmd)
=======
1.  Burak
>>>>>>> Stashed changes

2.  Burak

3.  Eda

4.  [Sebastian Szymański](/takim/szymanski.qmd)

<<<<<<< Updated upstream
## Proje Adı

MUY660-İş Analitiği iyileştirme çalışmaları (örnek)
=======
5.  [Sevtap Gokce](/takim/SevtapGokce.qmd)

## Proje Adı

MUY665-İş Analitiği iyileştirme çalışmaları (örnek)
>>>>>>> Stashed changes

## Proje Konusu

Örnek: Bu projede MUY660-İş Analitiği ders içeriğinin analitik yaklaşımlarla iyileştirilmesini hedefledik. Bu doğrultuda tüm üniversitelerdeki benzer derslerin verisini toplayarak bir veri seti oluşturduk Analiz için ........ yöntemleri kullanarak, ....... çalışmaları yaptık Sonuç olarak, MUY660-İş Analitiği dersinin dünyadaki tüm derslerden daha iyi olduğunu ve bu dersi aldığımız için çok mutlu olduğumuzu tespit ettik.

## Veri Seti Hakkında Özet Bilgi

## Sonuçlar

Burada key takeways verilmelidir. En az 3 en fazla 5 madde ile çarpıcı sonuçlar sunulmalıdır.
